version: '3'
tasks:

  build:
    desc: Build book
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f jdp-book.toml
    cmds:
      - jdp epub build-project --directory ../../../out
  
  pdf:
    desc: Convert books to A5 PDF
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        set -e
        for book in *.epub; do
          ebook-convert.exe ${book} ${book%.epub}.pdf --paper-size a5 --pdf-page-margin-bottom 36 --pdf-page-margin-left 24 --pdf-page-margin-right 24 --pdf-page-margin-top 24 --pdf-page-numbers
        done

