identifier = '5fae2c86-0835-4597-8d25-e0595d7ab705'
title = 'Verdadera historia de los sucesos de la conquista de la Nueva-España'
filename = 'bernal_diaz-verdadera_historia_de_la_conquista.epub'
language = 'es'

cover = 'cover.svg'
template = '../../tpl/latn'

author = [
  'Bernal Díaz del Castillo'
]

stylesheet = [
  '../../css/latn/nav.css',
  '../../css/latn/default.css',
  '../../css/latn/section.css',
  '../../css/latn/dialog.css',
  '../../css/latn/parallel-text.css'
]

font = [
]

image = [
]

[[section]]
head = 'part1.md'
text = [
  '000.md',
  '001.md',
  '002.md',
  '003.md',
  '004.md',
  '005.md',
  '006.md',
  '007.md',
  '008.md',
  '009.md',
  '010.md',
  '011.md',
  '012.md',
  '013.md',
  '014.md',
  '015.md',
  '016.md',
  '017.md',
  '018.md',
  '019.md',
  '020.md',
  '021.md',
  '022.md',
  '023.md',
  '024.md',
  '025.md',
  '026.md',
  '027.md',
  '028.md',
  '029.md',
  '030.md',
  '031.md',
  '032.md',
  '033.md',
  '034.md',
  '035.md',
  '036.md',
  '037.md',
  '038.md',
  '039.md',
  '040.md',
  '041.md',
  '042.md',
  '043.md',
  '044.md',
  '045.md',
  '046.md',
  '047.md',
  '048.md',
  '049.md',
  '050.md',
  '051.md',
  '052.md',
  '053.md',
  '054.md',
  '055.md',
  '056.md',
  '057.md',
  '058.md',
  '059.md',
  '060.md',
  '061.md',
  '062.md',
  '063.md',
  '064.md',
  '065.md',
  '066.md',
  '067.md',
  '068.md',
  '069.md',
  '070.md',
  '071.md',
  '072.md',
  '073.md',
  '074.md',
  '075.md',
  '076.md',
  '077.md',
  '078.md',
  '079.md',
  '080.md',
  '081.md',
  '082.md',
  '083.md',
  '084.md',
  '085.md',
  '086.md',
  '087.md',
  '088.md',
  '089.md',
  '090.md',
  '091.md',
  '092.md',
  '093.md',
  '094.md',
  '095.md',
  '096.md',
  '097.md',
  '098.md',
  '099.md',
  '100.md',
  '101.md',
  '102.md',
  '103.md',
  '104.md',
  '105.md',
  '106.md',
  '107.md',
  '108.md',
  '109.md',
  '110.md',
  '111.md'
]

[[section]]
head = 'part2.md'
text = [
  '112.md',
  '113.md',
  '114.md',
  '115.md',
  '116.md',
  '117.md',
  '118.md',
  '119.md',
  '120.md',
  '121.md',
  '122.md',
  '123.md',
  '124.md',
  '125.md',
  '126.md',
  '127.md',
  '128.md',
  '129.md',
  '130.md'
]

[[section]]
head = 'part3.md'
text = [
]
